modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mixins]]
config="fluid.mixins.json"

[[mods]]
modId="fluid"
version="1.2.3"
displayName="Create Fluid"
logoFile="fluid.png"
credits="adonis"
authors="adonis"
description='''
Enhance fluid logistics and processing system for Create
'''

[[dependencies.fluid]]
modId="forge"
mandatory=true
versionRange="[47, )"
ordering="NONE"
side="BOTH"

[[dependencies.fluid]]
modId="create"
mandatory=true
versionRange="[6.0.2,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.fluid]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.20.2]"
ordering="NONE"
side="BOTH"