
modLoader="javafml" #mandatory

loaderVersion="[47,)"

license="MIT License"

[[mods]] #mandatory

modId="fluid" #mandatory


displayName="Create Fluid" #mandatory
logoFile="fluid.png" #optional

credits="adonis" #optional

authors="adonis" #optional

description='''
A Create mod addon that allows for automatic fishing and item collection
'''

[[dependencies.fluid]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47, )" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.fluid]]
modId="create" #mandatory
mandatory=true
versionRange="[6.0.2,6.1.0)"
ordering="NONE"
side="BOTH"
[[dependencies.fluid]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.20.2]"
ordering="NONE"
side="BOTH"
